# config file version
# http://docs.grafana.org/administration/provisioning/#datasources
apiVersion: 1

datasources:
- name: influxdb-dcts-monitoring
  type: influxdb
  access: proxy
  orgId: 1
  url: $INFLUXDB_URL
  password:
  user:
  database: dcts-monitoring
  basicAuth: false
  editable: true

- name: influx
  type: influxdb
  access: proxy
  orgId: 1
  url: $INFLUXDB_URL
  password:
  user:
  database: telegraf
  basicAuth: false
  editable: true
