version: '3'
services:

  mirror-registry:
    container_name: mirror-registry
    restart: always
    image: registry:2
    ports:
      - 5555:5000
    environment:
      # how to override configuration
      # https://docs.docker.com/registry/configuration/#override-specific-configuration-options
      # https://github.com/docker/distribution/blob/master/docs/configuration.md
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    volumes:
      - /opt/docker_volumes/registry/mirror.registry/data:/var/lib/registry
      - /opt/docker_volumes/registry/mirror.registry/certs:/certs

  bluesky-private-registry:
    container_name: bluesky-private-registry
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      # how to override configuration
      # https://docs.docker.com/registry/configuration/#override-specific-configuration-options
      # https://github.com/docker/distribution/blob/master/docs/configuration.md
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - /opt/docker_volumes/registry/blue.sky/data:/var/lib/registry
      - /opt/docker_volumes/registry/blue.sky/certs:/certs
